repro import error
Demonstrate the error that occurs when attempting to import
XMonad.Util.ClickableWorkspaces, since that module is not listed in
xmonad-contrib.cabal

Attempting to compile yields the following error:

  config.hs:4:1: error:
      Could not find module ‘XMonad.Util.ClickableWorkspaces’
      Use -v to see a list of the files searched for.
    |
  4 | import XMonad.Util.ClickableWorkspaces (clickablePP)
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^